FROM python:3.6.3

# install environment dependencies
RUN apt-get update -yqq \
&& apt-get install -yqq --no-install-recommends \
netcat \
&& apt-get -q clean \
&& apt-get install -y dos2unix

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add entrypoint.sh
#RUN sudo chmod +x ./entrypoint.sh
ADD ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod 0777 /usr/src/app/entrypoint.sh


RUN dos2unix ./entrypoint.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

# add requirements
ADD ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt


# add app
ADD . /usr/src/app


# run server
#CMD ["chmod", "+x","./entrypoint.sh"]
CMD ["./entrypoint.sh"]